aaaaaaaaaaA

diff --git a/bin/butter_pkg b/bin/butter_pkg
--- a/bin/butter_pkg
+++ b/bin/butter_pkg
@@ -1,11 +1,3 @@
-// ButterScript v0.1.0
-const termutils = require('./lib/butter_modules/termutils/index')
-termutils.write("ButterScript v0.1.1\n");
-termutils.write("ButterScript is licensed with the GPL-2.0 license.\n");
-termutils.write(">>  ");
-
-async function startrepl() {
-    var repl = await termutils.read()
-    termutils.write("[ERROR] Option not supported: " + repl + "\n")
-} 
-startrepl();
+#!/bin/bash
+echo "[ERROR] butter_pkg is in progress (dismissed for now)"
+exit 1
